# Generated by Django 2.2 on 2021-01-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210128_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addressfield1',
            new_name='address_1',
        ),
    ]
