# Generated by Django 2.2 on 2021-05-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0018_ar03_ar04_ar05_ar06_iinflc01'),
        ('users', '0004_auto_20210128_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assays.Facility'),
        ),
    ]
