# Generated by Django 2.2 on 2020-07-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('staff', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('measurement_day', models.DateField(blank=True, null=True)),
                ('rawdata_file', models.FileField(upload_to='assays/xlsx/')),
                ('assayqc', models.CharField(blank=True, db_column='assayQC', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('facility', models.CharField(blank=True, max_length=16, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('staff', models.CharField(blank=True, max_length=256, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('assay_word', models.FileField(upload_to='assays/types/files/')),
                ('purpose', models.TextField(blank=True, null=True)),
                ('experimental_design', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('supplies', models.TextField(blank=True, null=True)),
                ('procedures', models.TextField(blank=True, null=True)),
                ('troubleshooting', models.TextField(blank=True, null=True)),
                ('appendix', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=128, null=True)),
                ('strain', models.CharField(blank=True, max_length=128, null=True)),
                ('tail_num', models.IntegerField(blank=True, null=True)),
                ('genotype', models.CharField(blank=True, max_length=128, null=True)),
                ('induced', models.CharField(blank=True, max_length=32, null=True)),
                ('treated', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dateofBirth', models.DateField(blank=True, null=True)),
                ('diet', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('health_report', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iinflc04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('timepoint_type', models.CharField(max_length=16)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.DO_NOTHING, to='assays.Mouse')),
            ],
            options={
                'db_table': 'IINFLC-04',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='assay',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='assays.Atype'),
        ),
    ]
