# Generated by Django 2.2 on 2021-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0003_fc08'),
    ]

    operations = [
        migrations.AddField(
            model_name='fc08',
            name='sample_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
