# Generated by Django 2.2 on 2020-09-25 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0004_auto_20200915_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='author',
            field=models.ForeignKey(db_column='author', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iinflc04',
            name='assayid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.Assay'),
        ),
        migrations.AlterField(
            model_name='iinflc04',
            name='mid',
            field=models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse'),
        ),
    ]
