# Generated by Django 2.2 on 2021-04-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0005_ar02'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='mouse_age',
            field=models.CharField(choices=[('days', 'days'), ('weeks', 'weeks')], default='days', max_length=7),
        ),
        migrations.AddField(
            model_name='assay',
            name='timesteps_in',
            field=models.CharField(choices=[('days', 'days'), ('weeks', 'weeks')], default='days', max_length=7),
        ),
    ]
