# Generated by Django 2.2 on 2020-09-25 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0005_auto_20200925_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='author',
            field=models.ForeignKey(db_column='author', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
