# Generated by Django 2.2 on 2021-04-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0006_auto_20210401_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
