# Generated by Django 2.2 on 2020-09-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0006_auto_20200925_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='iinflc04',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
