# Generated by Django 2.2 on 2021-04-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0007_assay_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='timesteps_in',
            field=models.CharField(choices=[('hours', 'hours'), ('days', 'days'), ('weeks', 'weeks')], default='days', max_length=7),
        ),
    ]
