# Generated by Django 2.2 on 2020-09-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0007_iinflc04_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iinflc04',
            name='comments',
        ),
    ]
