# Generated by Django 2.2 on 2021-04-02 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0008_auto_20210401_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='scientist',
            field=models.ForeignKey(blank=True, db_column='scientist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientists', related_query_name='scientist', to=settings.AUTH_USER_MODEL),
        ),
    ]
