# Generated by Django 2.2 on 2020-09-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0008_remove_iinflc04_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='health_report',
        ),
    ]
