# Generated by Django 2.2 on 2021-04-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0009_auto_20210402_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='assays/img/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_images', to='assays.Assay')),
            ],
            options={
                'managed': True,
                'db_table': 'AssociatedImages',
            },
        ),
    ]
