# Generated by Django 2.2 on 2020-09-29 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0010_auto_20200929_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ni02Rot01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('individual_latency_fall1', models.FloatField(blank=True, null=True)),
                ('individual_latency_fall2', models.FloatField(blank=True, null=True)),
                ('mean_latency_fall', models.FloatField(blank=True, null=True)),
                ('speed_fall1', models.FloatField(blank=True, null=True)),
                ('speed_fall2', models.FloatField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'NI-02_ROT-01',
            },
        ),
    ]
