# Generated by Django 2.2 on 2021-04-16 11:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0010_associatedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atype',
            name='appendix',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atype',
            name='equipment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atype',
            name='experimental_design',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atype',
            name='procedures',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atype',
            name='purpose',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atype',
            name='references',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atype',
            name='supplies',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atype',
            name='troubleshooting',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
