# Generated by Django 2.2 on 2020-09-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0011_ni02rot01'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ni02rot01',
            table='NI-02-ROT-01',
        ),
    ]
