# Generated by Django 2.2 on 2020-09-29 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0012_auto_20200929_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
