# Generated by Django 2.2 on 2021-04-30 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0012_iinflc05_iinflc06'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pr02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('mg_feacal_mass', models.FloatField(blank=True, null=True)),
                ('protein_concentration', models.FloatField(blank=True, null=True)),
                ('digestion_protocol', models.CharField(blank=True, max_length=256, null=True)),
                ('amount_injected', models.FloatField(blank=True, null=True)),
                ('lc_ms_analysis_time', models.FloatField(blank=True, null=True)),
                ('instrument_method', models.CharField(blank=True, max_length=256, null=True)),
                ('total_bac_signal', models.FloatField(blank=True, null=True)),
                ('firmicutes_per', models.FloatField(blank=True, null=True)),
                ('bacteroidetes_per', models.FloatField(blank=True, null=True)),
                ('firm_bac_ratio', models.FloatField(blank=True, null=True)),
                ('proteobacteria_per', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr02s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'PR-02',
            },
        ),
        migrations.CreateModel(
            name='Fc07',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('sample_source', models.CharField(blank=True, max_length=32, null=True)),
                ('facs_lysing', models.CharField(blank=True, max_length=32, null=True)),
                ('live_aquis', models.CharField(blank=True, max_length=16, null=True)),
                ('total_cell_count', models.FloatField(blank=True, null=True)),
                ('neu_per', models.FloatField(blank=True, null=True)),
                ('eos_per', models.FloatField(blank=True, null=True)),
                ('mon_per', models.FloatField(blank=True, null=True)),
                ('ly6chimono_per', models.FloatField(blank=True, null=True)),
                ('ly6cintermono_per', models.FloatField(blank=True, null=True)),
                ('ly6clowmono_per', models.FloatField(blank=True, null=True)),
                ('b_cells_per', models.FloatField(blank=True, null=True)),
                ('cd8_t_per', models.FloatField(blank=True, db_column='cd8_T_per', null=True)),
                ('cd4_t_per', models.FloatField(blank=True, db_column='cd4_T_per', null=True)),
                ('neu_num', models.FloatField(blank=True, null=True)),
                ('eos_num', models.FloatField(blank=True, null=True)),
                ('mon_num', models.FloatField(blank=True, null=True)),
                ('ly6chimono_num', models.FloatField(blank=True, null=True)),
                ('ly6cintermono_num', models.FloatField(blank=True, null=True)),
                ('ly6clowmono_num', models.FloatField(blank=True, null=True)),
                ('b_cells_num', models.FloatField(blank=True, null=True)),
                ('cd8_t_num', models.FloatField(blank=True, db_column='cd8_T_num', null=True)),
                ('cd4_t_num', models.FloatField(blank=True, db_column='cd4_T_num', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc07s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'FC-07',
            },
        ),
    ]
