# Generated by Django 2.2 on 2020-09-29 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0013_auto_20200929_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assay',
            name='author',
            field=models.ForeignKey(db_column='author', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
