# Generated by Django 2.2 on 2021-05-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0014_cba01_cba02'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hpibd03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('histology_num', models.IntegerField(blank=True, null=True)),
                ('si_inflammation_score', models.FloatField(blank=True, null=True)),
                ('colon_inflammation_score', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpibd03s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'HPIBD-03',
                'managed': True,
            },
        ),
    ]
