# Generated by Django 2.2 on 2021-05-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0015_hpibd03'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hpibd04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('slide_number', models.IntegerField(blank=True, null=True)),
                ('leukocyte_density_1', models.FloatField(blank=True, null=True)),
                ('leukocyte_density_2', models.FloatField(blank=True, null=True)),
                ('leukocyte_density_3', models.FloatField(blank=True, null=True)),
                ('leukocyte_density_avg', models.FloatField(blank=True, null=True)),
                ('level_1', models.FloatField(blank=True, null=True)),
                ('level_2', models.FloatField(blank=True, null=True)),
                ('level_3', models.FloatField(blank=True, null=True)),
                ('level_avg', models.FloatField(blank=True, null=True)),
                ('extent_1', models.FloatField(blank=True, null=True)),
                ('extent_2', models.FloatField(blank=True, null=True)),
                ('extent_3', models.FloatField(blank=True, null=True)),
                ('extent_avg', models.FloatField(blank=True, null=True)),
                ('inflammation_score', models.FloatField(blank=True, null=True)),
                ('abscesses', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpibd04s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'HPIBD-04',
            },
        ),
        migrations.CreateModel(
            name='Hpibd01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('colon_length', models.FloatField(blank=True, null=True)),
                ('histology_num', models.FloatField(blank=True, null=True)),
                ('inflammation_score', models.IntegerField(blank=True, null=True)),
                ('tissue_damage_score', models.IntegerField(blank=True, null=True)),
                ('ulceration_score', models.IntegerField(blank=True, null=True)),
                ('involvement_per', models.FloatField(blank=True, null=True)),
                ('total_colitis_score', models.IntegerField(blank=True, null=True)),
                ('tumor_num', models.IntegerField(blank=True, null=True)),
                ('tumor_size', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpibd01s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'HPIBD-01',
            },
        ),
    ]
