# Generated by Django 2.2 on 2021-05-02 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0016_hpibd01_hpibd04'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endo01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('thicken_colon', models.FloatField(blank=True, null=True)),
                ('changes_vascular', models.CharField(blank=True, max_length=255, null=True)),
                ('fibrin_visible', models.FloatField(blank=True, null=True)),
                ('granularity_mucosak', models.FloatField(blank=True, null=True)),
                ('stool_consistency', models.FloatField(blank=True, null=True)),
                ('total_colitis_score', models.FloatField(blank=True, null=True)),
                ('num_tumor_size_1', models.FloatField(blank=True, null=True)),
                ('num_tumor_size_2', models.FloatField(blank=True, null=True)),
                ('num_tumor_size_3', models.FloatField(blank=True, null=True)),
                ('num_tumor_size_4', models.FloatField(blank=True, null=True)),
                ('num_tumor_size_5', models.FloatField(blank=True, null=True)),
                ('total_tumor_num', models.FloatField(blank=True, null=True)),
                ('tumor_load', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endo01s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'ENDO-01',
                'managed': True,
            },
        ),
    ]
