# Generated by Django 2.2 on 2020-10-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0016_atype_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iinflc04',
            name='assayid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iinflc04s', to='assays.Assay'),
        ),
    ]
