# Generated by Django 2.2 on 2021-05-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0017_endo01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iinflc01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('stool_consistency', models.FloatField(blank=True, null=True)),
                ('blood_in_stool', models.FloatField(blank=True, null=True)),
                ('weight_score', models.FloatField(blank=True, null=True)),
                ('dai', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iinflc01s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'IINFLC-01',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ar06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('clinical_score', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar06s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'AR-06',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ar05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('bvtv', models.FloatField(blank=True, null=True)),
                ('bstv', models.FloatField(blank=True, null=True)),
                ('trabecular_thickness', models.FloatField(blank=True, null=True)),
                ('trabecular_number', models.FloatField(blank=True, null=True)),
                ('trabecular_seperation', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar05s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'AR-05',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ar04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('sum_intensity', models.FloatField(blank=True, null=True)),
                ('net_intensity', models.FloatField(blank=True, null=True)),
                ('mean_intensity', models.FloatField(blank=True, null=True)),
                ('acquisition_settings', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar04s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'AR-04',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ar03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('sum_intensity_fl', models.FloatField(blank=True, null=True)),
                ('net_intensity_fl', models.FloatField(blank=True, null=True)),
                ('sum_intensity_hl', models.FloatField(blank=True, null=True)),
                ('net_intensity_hl', models.FloatField(blank=True, null=True)),
                ('sum_intensity_total', models.FloatField(blank=True, null=True)),
                ('net_intensity_total', models.FloatField(blank=True, null=True)),
                ('acquisition_settings', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar03s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'AR-03',
                'managed': True,
            },
        ),
    ]
