# Generated by Django 2.2 on 2020-10-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0018_auto_20201004_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ni02ofd01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('total_distance_wa', models.FloatField(blank=True, null=True)),
                ('total_distance_cz', models.FloatField(blank=True, null=True)),
                ('total_distance_pz', models.FloatField(blank=True, null=True)),
                ('total_rears', models.FloatField(blank=True, null=True)),
                ('rears_cz', models.FloatField(blank=True, null=True)),
                ('rears_pz', models.FloatField(blank=True, null=True)),
                ('time_cz', models.FloatField(blank=True, null=True)),
                ('time_pz', models.FloatField(blank=True, null=True)),
                ('duration_immobility_wa', models.FloatField(blank=True, null=True)),
                ('duration_immobility_cz', models.FloatField(blank=True, null=True)),
                ('duration_immobility_pz', models.FloatField(blank=True, null=True)),
                ('avg_speed_wa', models.FloatField(blank=True, null=True)),
                ('avg_speed_cz', models.FloatField(blank=True, null=True)),
                ('avg_speed_pz', models.FloatField(blank=True, null=True)),
                ('num_entries_cz', models.FloatField(blank=True, null=True)),
                ('latency1_cz', models.FloatField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ni02ofd01s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'NI-02-OFD-01',
            },
        ),
    ]
