# Generated by Django 2.2 on 2021-05-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0019_ar07'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cba03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('parameter1', models.FloatField(blank=True, null=True)),
                ('parameter2', models.FloatField(blank=True, null=True)),
                ('parameter3', models.FloatField(blank=True, null=True)),
                ('parameter4', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cba03s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'CBA-03',
            },
        ),
    ]
