# Generated by Django 2.2 on 2021-05-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0020_cba03'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar03',
            name='sum_intensity_fl',
            field=models.FloatField(blank=True, null=True, verbose_name='sum intensity (FL)'),
        ),
        migrations.CreateModel(
            name='Hpa02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('synovitis', models.FloatField(blank=True, null=True)),
                ('cartilage_destruction', models.FloatField(blank=True, null=True)),
                ('bone_erosion', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpa02s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'HPA-02',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fc01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('sample_source', models.CharField(blank=True, max_length=64, null=True)),
                ('live_aquis', models.CharField(blank=True, max_length=64, null=True)),
                ('total_cell_count', models.FloatField(blank=True, null=True)),
                ('neu_per', models.FloatField(blank=True, null=True)),
                ('eos_per', models.FloatField(blank=True, null=True)),
                ('mon_per', models.FloatField(blank=True, null=True)),
                ('recent_emigrant_monocytes_per', models.FloatField(blank=True, null=True)),
                ('inflammatory_monocytes_per', models.FloatField(blank=True, null=True)),
                ('steady_state_monocytes_per', models.FloatField(blank=True, null=True)),
                ('nk_cells_per', models.FloatField(blank=True, null=True)),
                ('b_cells_per', models.FloatField(blank=True, null=True)),
                ('t_cells_per', models.FloatField(blank=True, null=True)),
                ('b1b_cells_per', models.FloatField(blank=True, null=True)),
                ('b2b_cells_per', models.FloatField(blank=True, null=True)),
                ('dcs_per', models.FloatField(blank=True, null=True)),
                ('cds_per', models.FloatField(blank=True, null=True)),
                ('cds_cd11_per', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('pdcs_per', models.FloatField(blank=True, null=True)),
                ('macrophages_per', models.FloatField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc01s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'FC-01',
                'managed': True,
            },
        ),
    ]
