# Generated by Django 2.2 on 2020-10-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0020_auto_20201005_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hem01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('wbc_count', models.FloatField(blank=True, null=True)),
                ('mononuclear_num', models.FloatField(blank=True, null=True)),
                ('lymphocytes_num', models.FloatField(blank=True, null=True)),
                ('lymphocytes_per', models.FloatField(blank=True, null=True)),
                ('monocytes_num', models.FloatField(blank=True, null=True)),
                ('monocytes2_num', models.FloatField(blank=True, null=True)),
                ('neutrophils_num', models.FloatField(blank=True, null=True)),
                ('neutrophils_per', models.FloatField(blank=True, null=True)),
                ('eosinophils_num', models.FloatField(blank=True, null=True)),
                ('eosinophils_per', models.FloatField(blank=True, null=True)),
                ('basophils_num', models.FloatField(blank=True, null=True)),
                ('basophils_per', models.FloatField(blank=True, null=True)),
                ('rbc_count', models.FloatField(blank=True, null=True)),
                ('ht', models.FloatField(blank=True, null=True)),
                ('hb', models.FloatField(blank=True, null=True)),
                ('plt_count', models.FloatField(blank=True, null=True)),
                ('platelet_dist_range', models.FloatField(blank=True, null=True)),
                ('platelet_count', models.FloatField(blank=True, null=True)),
                ('avg_vol_platelets', models.FloatField(blank=True, null=True)),
                ('mcv', models.FloatField(blank=True, null=True)),
                ('pdv', models.FloatField(blank=True, null=True)),
                ('mchc', models.FloatField(blank=True, null=True)),
                ('mcv2', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hem01s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'HEM-01',
            },
        ),
    ]
