# Generated by Django 2.2 on 2020-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0021_hem01'),
    ]

    operations = [
        migrations.AddField(
            model_name='hem01',
            name='sample_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
