# Generated by Django 2.2 on 2021-05-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0021_auto_20210524_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fc03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('sample_source', models.CharField(blank=True, max_length=64, null=True)),
                ('live_aquis', models.CharField(blank=True, max_length=64, null=True)),
                ('total_cell_count', models.FloatField(blank=True, null=True)),
                ('total_b_cells', models.FloatField(blank=True, null=True)),
                ('b1b_cells_per', models.FloatField(blank=True, null=True)),
                ('b2b_cells_per', models.FloatField(blank=True, null=True)),
                ('b2b_immature_cells_per', models.FloatField(blank=True, null=True)),
                ('t1_cells_per', models.FloatField(blank=True, null=True)),
                ('mzb_cells_per', models.FloatField(blank=True, null=True)),
                ('b2_mature_cells_per', models.FloatField(blank=True, null=True)),
                ('t2_cells_per', models.FloatField(blank=True, null=True)),
                ('t3_cells_per', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc03s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'FC-03',
                'managed': True,
            },
        ),
    ]
