# Generated by Django 2.2 on 2021-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0023_fc04_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='mid',
            field=models.CharField(max_length=128),
        ),
    ]
