# Generated by Django 2.2 on 2020-10-05 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0023_auto_20201005_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='scientist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientists', related_query_name='scientist', to=settings.AUTH_USER_MODEL),
        ),
    ]
