# Generated by Django 2.2 on 2020-10-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0024_assay_scientist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iinflc02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('sample_source', models.CharField(blank=True, max_length=256, null=True)),
                ('cell_count_s_intestine', models.FloatField(blank=True, null=True)),
                ('cell_count_l_intestine', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iinflc02s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'IINFLC-02',
                'managed': True,
            },
        ),
    ]
