# Generated by Django 2.2 on 2020-10-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0025_iinflc02'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hpibd02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('inflammation_small', models.FloatField(blank=True, null=True)),
                ('epithelial_small', models.FloatField(blank=True, null=True)),
                ('inflammation_large', models.FloatField(blank=True, null=True)),
                ('epithelial_large', models.FloatField(blank=True, null=True)),
                ('vc_ratio', models.FloatField(blank=True, null=True)),
                ('colon_length', models.FloatField(blank=True, null=True)),
                ('epithelium_s_flattening', models.FloatField(blank=True, null=True)),
                ('apoptotic_s_field', models.FloatField(blank=True, null=True)),
                ('goblet_s_depletion', models.FloatField(blank=True, null=True)),
                ('lumen_s_exfoliation', models.FloatField(blank=True, null=True)),
                ('villus_s_short', models.FloatField(blank=True, null=True)),
                ('igd_small', models.FloatField(blank=True, null=True)),
                ('paneth_s_activation', models.FloatField(blank=True, null=True)),
                ('peyer_s_patch', models.FloatField(blank=True, null=True)),
                ('apoptotic_l_field', models.FloatField(blank=True, null=True)),
                ('goblet_l_depletion', models.FloatField(blank=True, null=True)),
                ('lumen_l_exfoliation', models.FloatField(blank=True, null=True)),
                ('crypt_l_damage', models.FloatField(blank=True, null=True)),
                ('endothelial_l_activation', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpibd02s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'db_table': 'HPIBD-02',
                'managed': True,
            },
        ),
    ]
