# Generated by Django 2.2 on 2021-07-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0026_auto_20210708_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atype',
            old_name='unit',
            new_name='service_type',
        ),
    ]
