# Generated by Django 2.2 on 2021-07-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0027_auto_20210708_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='scientist',
        ),
        migrations.AddField(
            model_name='assay',
            name='scientist_in_charge',
            field=models.ForeignKey(blank=True, db_column='scientist_in_charge', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientists', related_query_name='scientist_in_charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
