# Generated by Django 2.2 on 2021-07-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0028_auto_20210709_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='rawdata_file',
            field=models.FileField(blank=True, null=True, upload_to='assays/xlsx/'),
        ),
    ]
