# Generated by Django 2.2 on 2021-07-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0029_auto_20210709_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='rawdata_file',
            field=models.FileField(upload_to='assays/xlsx/'),
        ),
    ]
