# Generated by Django 2.2 on 2021-07-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0030_auto_20210719_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='rawdata_file',
            field=models.FileField(blank=True, null=True, upload_to='assays/xlsx/'),
        ),
    ]
