# Generated by Django 2.2 on 2022-02-21 08:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0031_auto_20210721_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('introduction', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reportassay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assays.Assay')),
            ],
        ),
    ]
