# Generated by Django 2.2 on 2022-03-03 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0032_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='members',
            field=models.ManyToManyField(blank=True, db_column='members', null=True, related_name='members', related_query_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
