# Generated by Django 2.2 on 2020-10-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0032_auto_20201006_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biochem05',
            old_name='anylase',
            new_name='amylase',
        ),
    ]
