# Generated by Django 2.2 on 2022-03-03 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0033_assay_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='members',
            field=models.ManyToManyField(blank=True, db_column='members', default=models.ForeignKey(db_column='author', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_user', to=settings.AUTH_USER_MODEL), null=True, related_name='members', related_query_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
