# Generated by Django 2.2 on 2020-10-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0034_auto_20201006_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='biochem06',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochem07',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochem08',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biochem07',
            name='sample_source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
