# Generated by Django 2.2 on 2022-03-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0035_auto_20220303_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='GI06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('firmicutes', models.FloatField(blank=True, null=True)),
                ('bacteroidetes', models.FloatField(blank=True, null=True)),
                ('proteobacteria', models.FloatField(blank=True, null=True)),
                ('firmicutes_bacteroidetes_ratio', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gi06s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'GI-06',
            },
        ),
        migrations.CreateModel(
            name='GI05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('fecal_cfus', models.FloatField(blank=True, null=True)),
                ('spleen_cfus', models.FloatField(blank=True, null=True)),
                ('spleen_weight', models.FloatField(blank=True, null=True)),
                ('body_weight', models.FloatField(blank=True, null=True)),
                ('spleen_body_ratio', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gi05s', to='assays.Assay')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='assays.Mouse')),
            ],
            options={
                'managed': True,
                'db_table': 'GI-05',
            },
        ),
    ]
