# Generated by Django 2.2 on 2022-03-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0036_gi05_gi06'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hem01',
            old_name='avg_vol_platelets',
            new_name='mch',
        ),
        migrations.RenameField(
            model_name='hem01',
            old_name='mcv2',
            new_name='mpv',
        ),
        migrations.RenameField(
            model_name='hem01',
            old_name='platelet_count',
            new_name='pct',
        ),
        migrations.RenameField(
            model_name='hem01',
            old_name='platelet_dist_range',
            new_name='pdw',
        ),
        migrations.RenameField(
            model_name='hem01',
            old_name='plt_count',
            new_name='plt',
        ),
        migrations.RenameField(
            model_name='hem01',
            old_name='rdv',
            new_name='rdwcv',
        ),
        migrations.AddField(
            model_name='hem01',
            name='rdwsd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
