# Generated by Django 2.2 on 2022-03-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0037_auto_20220328_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hem01',
            name='monocytes2_num',
        ),
    ]
