# Generated by Django 2.2 on 2020-10-08 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pi',
            field=models.ForeignKey(db_column='pi', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pipelines', to=settings.AUTH_USER_MODEL),
        ),
    ]
