# Generated by Django 2.2 on 2021-06-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Done')], default='Pending', max_length=32),
        ),
    ]
