# Generated by Django 2.2 on 2021-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_auto_20210605_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=32),
        ),
    ]
