# Generated by Django 2.2 on 2020-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='assays/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='assays/covers/')),
            ],
        ),
    ]
